ALTER TABLE ES_GOODS ADD GOOD_LV VARCHAR(100) DEFAULT NULL;
ALTER TABLE ES_GOODS ADD GOOD_YEAR VARCHAR(100) DEFAULT NULL;
ALTER TABLE ES_GOODS ADD GOOD_ALCOHOL VARCHAR(100) DEFAULT NULL;
ALTER TABLE ES_GOODS ADD SPECS_TYPE VARCHAR(100) DEFAULT NULL;