--创建es_logi_info表
BEGIN
	EXECUTE IMMEDIATE 'DROP TRIGGER TIB_ES_LOGI_INFO';
	EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE ES_LOGI_INFO';
	EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
	EXECUTE IMMEDIATE 'DROP SEQUENCE S_ES_LOGI_INFO';
	EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE ES_LOGI_INFO (
  ID NUMBER(11) NOT NULL,
  COM VARCHAR(255) DEFAULT '', /*快递公司代码*/
  NU VARCHAR(255) DEFAULT '' /*快递单号*/,
  MESSAGE VARCHAR(500) DEFAULT '' /*提示信息*/,
  STATUS VARCHAR(50) DEFAULT '' /*状态*/,
  TIME VARCHAR(50) DEFAULT '' /*时间*/,
  CONTEXT VARCHAR(1000) DEFAULT '' /*物流信息*/,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE S_ES_LOGI_INFO;

CREATE TRIGGER "TIB_ES_LOGI_INFO" BEFORE INSERT
	ON ES_LOGI_INFO FOR EACH ROW
	DECLARE
	INTEGRITY_ERROR  EXCEPTION;
	ERRNO            INTEGER;
	ERRMSG           CHAR(200);
	MAXID						 INTEGER;
	BEGIN
		IF :NEW."ID" IS NULL THEN
			SELECT MAX("ID") INTO MAXID FROM ES_LOGI_INFO;
			SELECT S_ES_LOGI_INFO.NEXTVAL INTO :NEW."ID" FROM DUAL;
			IF MAXID>:NEW."ID" THEN
				LOOP
					SELECT S_ES_LOGI_INFO.NEXTVAL INTO :NEW."ID" FROM DUAL;
					EXIT WHEN MAXID<:NEW."ID";
				END LOOP;
			END IF;
		END IF;
	EXCEPTION
		WHEN INTEGRITY_ERROR THEN
			RAISE_APPLICATION_ERROR(ERRNO, ERRMSG);
END;