ALTER TABLE ES_MEMBER ADD XINGE_ACCOUNT VARCHAR(2000) DEFAULT NULL;
ALTER TABLE ES_MEMBER ADD CIRCLE_NUM NUMBER(11) DEFAULT NULL;
ALTER TABLE ES_MEMBER ADD HOBBY VARCHAR(2000) DEFAULT NULL;
ALTER TABLE ES_MEMBER ADD THIRDPART_ID VARCHAR(2000) DEFAULT NULL;
ALTER TABLE ES_MEMBER ADD DESCRIPTION VARCHAR(2000) DEFAULT NULL;