--创建es_tasting_note表
BEGIN
	EXECUTE IMMEDIATE 'DROP TRIGGER TIB_ES_TASTING_NOTE';
	EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE ES_TASTING_NOTE';
	EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
	EXECUTE IMMEDIATE 'DROP SEQUENCE S_ES_TASTING_NOTE';
	EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE ES_TASTING_NOTE (
  ID NUMBER(11) NOT NULL,
  TITLE VARCHAR(100) DEFAULT NULL ,
  INTRODUCE VARCHAR(200) DEFAULT NULL,
  DETAIL VARCHAR(500) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE S_ES_TASTING_NOTE;

CREATE TRIGGER "TIB_ES_TASTING_NOTE" BEFORE INSERT
	ON ES_TASTING_NOTE FOR EACH ROW
	DECLARE
	INTEGRITY_ERROR  EXCEPTION;
	ERRNO            INTEGER;
	ERRMSG           CHAR(200);
	MAXID	         INTEGER;
	BEGIN
		IF :NEW."ID" IS NULL THEN
			SELECT MAX("ID") INTO MAXID FROM ES_TASTING_NOTE;
			SELECT S_ES_TASTING_NOTE.NEXTVAL INTO :NEW."ID" FROM DUAL;
			IF MAXID>:NEW."ID" THEN
				LOOP
					SELECT S_ES_TASTING_NOTE.NEXTVAL INTO :NEW."ID" FROM DUAL;
					EXIT WHEN MAXID<:NEW."ID";
				END LOOP;
			END IF;
		END IF;
	EXCEPTION
		WHEN INTEGRITY_ERROR THEN
			RAISE_APPLICATION_ERROR(ERRNO, ERRMSG);
END;