--创建ES_UTASTING_NOTE表
BEGIN
	EXECUTE IMMEDIATE 'DROP TRIGGER TIB_ES_UTASTING_NOTE';
	EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE ES_UTASTING_NOTE';
	EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
	EXECUTE IMMEDIATE 'DROP SEQUENCE S_ES_UTASTING_NOTE';
	EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE ES_UTASTING_NOTE (
  ID NUMBER(11) NOT NULL,
  WINE_NAME VARCHAR(100) DEFAULT NULL,
  TASTING_TIME VARCHAR(100) DEFAULT NULL,
  APPEARANCE1 VARCHAR(200) DEFAULT NULL,
  APPEARANCE2 VARCHAR(200) DEFAULT NULL,
  APPEARANCE3 VARCHAR(200) DEFAULT NULL,
  QUALITY1 VARCHAR(200) DEFAULT NULL,
  QUALITY2 VARCHAR(200) DEFAULT NULL,
  QUALITY3 VARCHAR(200) DEFAULT NULL,
  BRAND1 VARCHAR(200) DEFAULT NULL,
  BRAND2 VARCHAR(200) DEFAULT NULL,
  BRAND3 VARCHAR(200) DEFAULT NULL, 
  PRICE1 VARCHAR(200) DEFAULT NULL,
  PRICE2 VARCHAR(200) DEFAULT NULL,
  PRICE3 VARCHAR(200) DEFAULT NULL,
  APPRAISE1 VARCHAR(200) DEFAULT NULL,
  APPRAISE2 VARCHAR(200) DEFAULT NULL,
  APPRAISE3 VARCHAR(200) DEFAULT NULL,
  SCORE1 VARCHAR(200) DEFAULT NULL,
  SCORE2 VARCHAR(200) DEFAULT NULL,
  SCORE3 VARCHAR(200) DEFAULT NULL, 
  IMAGES1 VARCHAR(200) DEFAULT NULL,
  IMAGES2 VARCHAR(200) DEFAULT NULL,
  IMAGES3 VARCHAR(200) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE S_ES_UTASTING_NOTE;

CREATE TRIGGER "TIB_ES_UTASTING_NOTE" BEFORE INSERT
	ON ES_UTASTING_NOTE FOR EACH ROW
	DECLARE
	INTEGRITY_ERROR  EXCEPTION;
	ERRNO            INTEGER;
	ERRMSG           CHAR(200);
	MAXID	         INTEGER;
	BEGIN
		IF :NEW."ID" IS NULL THEN
			SELECT MAX("ID") INTO MAXID FROM ES_UTASTING_NOTE;
			SELECT S_ES_UTASTING_NOTE.NEXTVAL INTO :NEW."ID" FROM DUAL;
			IF MAXID>:NEW."ID" THEN
				LOOP
					SELECT S_ES_UTASTING_NOTE.NEXTVAL INTO :NEW."ID" FROM DUAL;
					EXIT WHEN MAXID<:NEW."ID";
				END LOOP;
			END IF;
		END IF;
	EXCEPTION
		WHEN INTEGRITY_ERROR THEN
			RAISE_APPLICATION_ERROR(ERRNO, ERRMSG);
END;