--创建ES_CF_CLICK表
BEGIN
	EXECUTE IMMEDIATE 'DROP TRIGGER TIB_ES_CF_CLICK';
	EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE ES_CF_CLICK';
	EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
	EXECUTE IMMEDIATE 'DROP SEQUENCE S_ES_CF_CLICK';
	EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE ES_CF_CLICK (
  ID NUMBER(100) NOT NULL,
  CF_ID NUMBER(100) NOT NULL,
  MEMBER_ID VARCHAR(200) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE S_ES_CF_CLICK;

CREATE TRIGGER "TIB_ES_CF_CLICK" BEFORE INSERT
	ON ES_CF_CLICK FOR EACH ROW
	DECLARE
	INTEGRITY_ERROR  EXCEPTION;
	ERRNO            INTEGER;
	ERRMSG           CHAR(200);
	MAXID						 INTEGER;
	BEGIN
		IF :NEW."ID" IS NULL THEN
			SELECT MAX("ID") INTO MAXID FROM ES_CF_CLICK;
			SELECT S_ES_CF_CLICK.NEXTVAL INTO :NEW."ID" FROM DUAL;
			IF MAXID>:NEW."ID" THEN
				LOOP
					SELECT S_ES_CF_CLICK.NEXTVAL INTO :NEW."ID" FROM DUAL;
					EXIT WHEN MAXID<:NEW."ID";
				END LOOP;
			END IF;
		END IF;
	EXCEPTION
		WHEN INTEGRITY_ERROR THEN
			RAISE_APPLICATION_ERROR(ERRNO, ERRMSG);
END;