--创建es_maimo表
BEGIN
	EXECUTE IMMEDIATE 'DROP TRIGGER TIB_ES_MAIMO';
	EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE ES_MAIMO';
	EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
	EXECUTE IMMEDIATE 'DROP SEQUENCE S_ES_MAIMO';
	EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE ES_MAIMO (
  ID NUMBER(20) NOT NULL ,
  TITLE VARCHAR(200) DEFAULT NULL,
  CONTENT VARCHAR(200) DEFAULT NULL,
  ADDRESS VARCHAR(200) DEFAULT NULL,
  PRICE VARCHAR(100) DEFAULT '',
  STATUS NUMBER(5) DEFAULT NULL,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE S_ES_MAIMO;

CREATE TRIGGER "TIB_ES_MAIMO" BEFORE INSERT
	ON ES_MAIMO FOR EACH ROW
	DECLARE
	INTEGRITY_ERROR  EXCEPTION;
	ERRNO            INTEGER;
	ERRMSG           CHAR(200);
	MAXID						 INTEGER;
	BEGIN
		IF :NEW."ID" IS NULL THEN
			SELECT MAX("ID") INTO MAXID FROM ES_MAIMO;
			SELECT S_ES_MAIMO.NEXTVAL INTO :NEW."ID" FROM DUAL;
			IF MAXID>:NEW."ID" THEN
				LOOP
					SELECT S_ES_MAIMO.NEXTVAL INTO :NEW."ID" FROM DUAL;
					EXIT WHEN MAXID<:NEW."ID";
				END LOOP;
			END IF;
		END IF;
	EXCEPTION
		WHEN INTEGRITY_ERROR THEN
			RAISE_APPLICATION_ERROR(ERRNO, ERRMSG);
END;