ALTER TABLE ES_ORDER ADD IS_STORAGE NUMBER(10) DEFAULT NULL;
ALTER TABLE ES_ORDER ADD START_STORAGE_TIME NUMBER(10) DEFAULT NULL;
ALTER TABLE ES_ORDER ADD END_STORAGE_TIME NUMBER(10) DEFAULT NULL;
ALTER TABLE ES_ORDER ADD STORAGE_DATE NUMBER(10) DEFAULT NULL;

