--创建es_sommelier_type表
BEGIN
	EXECUTE IMMEDIATE 'DROP TRIGGER TIB_ES_SOMMELIER_ORDER_TYPE';
	EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE ES_SOMMELIER_ORDER_TYPE';
	EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
	EXECUTE IMMEDIATE 'DROP SEQUENCE S_ES_SOMMELIER_ORDER_TYPE';
	EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE ES_SOMMELIER_ORDER_TYPE (
  ID NUMBER(30) NOT NULL,
  ORDER_TYPE_NAME VARCHAR(200) DEFAULT NULL,
  ORDER_TYPE_PRICE NUMBER(30) DEFAULT NULL,
  ORDER_TYPE_INTRO VARCHAR(1000) DEFAULT NULL,
  ORDER_TYPE_IMAGE VARCHAR(500) DEFAULT NULL
  PRIMARY KEY (ID)
);

CREATE SEQUENCE S_ES_SOMMELIER_ORDER_TYPE;

CREATE TRIGGER "TIB_ES_SOMMELIER_ORDER_TYPE" BEFORE INSERT
	ON ES_SOMMELIER_ORDER_TYPE FOR EACH ROW
	DECLARE
	INTEGRITY_ERROR  EXCEPTION;
	ERRNO            INTEGER;
	ERRMSG           CHAR(200);
	MAXID						 INTEGER;
	BEGIN
		IF :NEW."ID" IS NULL THEN
			SELECT MAX("ID") INTO MAXID FROM ES_SOMMELIER_ORDER_TYPE;
			SELECT S_ES_SOMMELIER_ORDER_TYPE.NEXTVAL INTO :NEW."ID" FROM DUAL;
			IF MAXID>:NEW."ID" THEN
				LOOP
					SELECT S_ES_SOMMELIER_ORDER_TYPE.NEXTVAL INTO :NEW."ID" FROM DUAL;
					EXIT WHEN MAXID<:NEW."ID";
				END LOOP;
			END IF;
		END IF;
	EXCEPTION
		WHEN INTEGRITY_ERROR THEN
			RAISE_APPLICATION_ERROR(ERRNO, ERRMSG);
END;