--创建es_sommelier_my_type表
BEGIN
	EXECUTE IMMEDIATE 'DROP TRIGGER TIB_ES_SOMMELIER_MY_TYPE';
	EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE ES_SOMMELIER_MY_TYPE';
	EXCEPTION WHEN OTHERS THEN NULL;
END;

BEGIN
	EXECUTE IMMEDIATE 'DROP SEQUENCE S_ES_SOMMELIER_MY_TYPE';
	EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE TABLE ES_SOMMELIER_MY_TYPE (
  ID NUMBER(30) NOT NULL,
  SOMMELIER_ID NUMBER(30) DEFAULT NULL,
  ORDER_TYPE_ID NUMBER(30) DEFAULT NULL,
  MY_PRICE NUMBER(38,2) DEFAULT NULL,
  STATUS NUMBER(1) DEFAULT 0,
  PRIMARY KEY (ID)
);

CREATE SEQUENCE S_ES_SOMMELIER_MY_TYPE;

CREATE TRIGGER "TIB_ES_SOMMELIER_MY_TYPE" BEFORE INSERT
	ON ES_SOMMELIER_MY_TYPE FOR EACH ROW
	DECLARE
	INTEGRITY_ERROR  EXCEPTION;
	ERRNO            INTEGER;
	ERRMSG           CHAR(200);
	MAXID						 INTEGER;
	BEGIN
		IF :NEW."ID" IS NULL THEN
			SELECT MAX("ID") INTO MAXID FROM ES_SOMMELIER_MY_TYPE;
			SELECT S_ES_SOMMELIER_MY_TYPE.NEXTVAL INTO :NEW."ID" FROM DUAL;
			IF MAXID>:NEW."ID" THEN
				LOOP
					SELECT S_ES_SOMMELIER_MY_TYPE.NEXTVAL INTO :NEW."ID" FROM DUAL;
					EXIT WHEN MAXID<:NEW."ID";
				END LOOP;
			END IF;
		END IF;
	EXCEPTION
		WHEN INTEGRITY_ERROR THEN
			RAISE_APPLICATION_ERROR(ERRNO, ERRMSG);
END;